ALTER TABLE account DROP COLUMN IF EXISTS name;
ALTER TABLE asset ALTER COLUMN current_price SET DATA TYPE DECIMAL(19, 10);
ALTER TABLE price_history ALTER COLUMN price SET DATA TYPE DECIMAL(19, 10);
ALTER TABLE asset_quantity ALTER COLUMN quantity SET DATA TYPE DECIMAL(19, 10);
